/*
 * Copyright (c) 2024 Angelo Cassano
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

import 'package:flutter_flavorizr/src/exception/malformed_resource_exception.dart';
import 'package:flutter_flavorizr/src/parser/models/flavors/flavor.dart';
import 'package:flutter_flavorizr/src/processors/commons/string_processor.dart';
import 'package:flutter_flavorizr/src/utils/desktop_utils.dart';

/// Wires `FLUTTER_APP_FLAVOR` (a CMake variable the Flutter tool defines at
/// configure time when `--flavor` is passed) to a per-flavor icon/window
/// title, then templates `Runner.rc`/`main.cpp` from their `.in` templates
/// (see `WindowsRunnerRcTemplateProcessor`/`WindowsMainCppTemplateProcessor`)
/// so the compiled resource picks them up.
class WindowsRunnerCMakeListsProcessor extends StringProcessor {
  static const _addExecutableAnchor = r'add_executable(${BINARY_NAME} WIN32';
  static final RegExp _addExecutable = RegExp(
    RegExp.escape(_addExecutableAnchor),
  );

  static const _beginMarkup =
      '# ----- BEGIN FLUTTER_APP_FLAVOR (autogenerated by flutter_flavorizr) -----';
  static const _endMarkup =
      '# ----- END FLUTTER_APP_FLAVOR (autogenerated by flutter_flavorizr) -----';

  WindowsRunnerCMakeListsProcessor({
    super.input,
    required super.config,
    required super.logger,
  });

  @override
  String execute() {
    logger.detail(
      '[$WindowsRunnerCMakeListsProcessor] Processing windows/runner/CMakeLists.txt',
    );

    final cleaned = _cleanupExistingBlock(input!);
    final anchorMatch = _addExecutable.firstMatch(cleaned);

    if (anchorMatch == null) {
      logger.detail(
        '[$WindowsRunnerCMakeListsProcessor] No `$_addExecutableAnchor` found in windows/runner/CMakeLists.txt',
        style: logger.theme.err,
      );

      throw MalformedResourceException(input!);
    }

    logger.detail(
      '[$WindowsRunnerCMakeListsProcessor] Found add_executable, injecting per-flavor icon/window title overrides',
    );

    final rest = stripLeadingLineBreaks(cleaned.substring(anchorMatch.start));
    final prefix = cleaned
        .substring(0, anchorMatch.start)
        .replaceFirst(RegExp(r'(?:\r?\n)+$'), '\n');

    final buffer = StringBuffer(prefix);
    _appendBlock(buffer);
    buffer.writeln();
    buffer.writeln();
    buffer.write(rest);

    logger.detail(
      '[$WindowsRunnerCMakeListsProcessor] windows/runner/CMakeLists.txt processed',
      style: logger.theme.success,
    );

    return buffer.toString();
  }

  String _cleanupExistingBlock(String content) =>
      cleanupMarkupBlock(content, _beginMarkup, _endMarkup);

  void _appendBlock(StringBuffer buffer) {
    buffer.writeln(_beginMarkup);
    buffer.writeln('if(DEFINED FLUTTER_APP_FLAVOR)');

    final entries = config.windowsFlavors.entries.toList(growable: false);
    for (int i = 0; i < entries.length; i++) {
      final MapEntry<String, Flavor> entry = entries[i];
      final keyword = i == 0 ? 'if' : 'elseif';

      buffer.writeln('  $keyword(FLUTTER_APP_FLAVOR STREQUAL "${entry.key}")');
      buffer.writeln(
        '    set(RUNNER_APP_ICON "${escapeQuotedString('${entry.key}.ico')}")',
      );
      buffer.writeln(
        '    set(WINDOW_TITLE "${escapeQuotedString(entry.value.app.name)}")',
      );
    }

    buffer.writeln('  endif()');
    buffer.writeln('else()');
    buffer.writeln('  set(RUNNER_APP_ICON "app_icon.ico")');
    buffer.writeln(r'  set(WINDOW_TITLE "${BINARY_NAME}")');
    buffer.writeln('endif()');
    buffer.writeln();
    buffer.writeln('configure_file(');
    buffer.writeln(
      r'  "${CMAKE_CURRENT_SOURCE_DIR}/Runner.rc.in"',
    );
    buffer.writeln(
      r'  "${CMAKE_CURRENT_SOURCE_DIR}/Runner.rc"',
    );
    buffer.writeln('  @ONLY');
    buffer.writeln(')');
    buffer.writeln('configure_file(');
    buffer.writeln(
      r'  "${CMAKE_CURRENT_SOURCE_DIR}/main.cpp.in"',
    );
    buffer.writeln(
      r'  "${CMAKE_CURRENT_SOURCE_DIR}/main.cpp"',
    );
    buffer.writeln('  @ONLY');
    buffer.writeln(')');
    buffer.write(_endMarkup);
  }

  @override
  String toString() => 'WindowsRunnerCMakeListsProcessor';
}
