name: Setup Flutter environment and get dependencies

inputs:
  platform:
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Use Flutter master (Linux/Windows flavor support isn't in a stable release yet)
      if: ${{ inputs.platform == 'linux' || inputs.platform == 'windows' }}
      shell: bash
      run: echo '{"flutter":"master"}' > .fvmrc

    - name: Install Flutter
      uses: kuhnroyal/flutter-fvm-config-action/setup@v3

    - name: Get dependencies
      shell: bash
      run: flutter pub get