include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
analyzer:
  exclude:
    - "blank/**"
    - "example/**"
    - "assets/**"
    - "test_resources/**"
    - "**/*.g.dart"
