include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
formatter:
  page_width: 80
analyzer:
  exclude:
    - "blank/**"
    - "example/**"
    - "assets/**"
    - "test_resources/**"
    - "**/*.g.dart"
