name: flutterflavorizr_example
description: Demonstrates how to use the flutterflavorizr plugin.
publish_to: 'none'

environment:
  sdk: "3.13.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_flavorizr:
    path: ../


flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type" # optional?

  flavors:
    apple:
      app:
        name: "Apple App"
        icon: "test_resources/commons/image_resizer_processor_test/source.png"

      android:
        applicationId: "com.example.apple"

      ios:
        bundleId: "com.example.apple"

    banana:
      app:
        name: "Banana App"

      android:
        applicationId: "com.example.banana"

      ios:
        bundleId: "com.example.banana"


flutter:
  uses-material-design: true
