/*
 * Copyright (c) 2024 Angelo Cassano
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

import 'package:flutter_flavorizr/src/exception/malformed_resource_exception.dart';
import 'package:flutter_flavorizr/src/processors/commons/string_processor.dart';
import 'package:flutter_flavorizr/src/utils/linux_utils.dart';

/// Forwards `FLUTTER_APP_FLAVOR` as a preprocessor define so
/// `my_application.cc` can read it via `#ifdef FLUTTER_APP_FLAVOR`. Freshly
/// generated `linux/runner/CMakeLists.txt` files don't do this on their own,
/// so it has to be injected here rather than assumed.
class LinuxRunnerCMakeListsProcessor extends StringProcessor {
  static const _applicationIdDefinitionAnchor =
      r'add_definitions(-DAPPLICATION_ID="${APPLICATION_ID}")';
  static final RegExp _applicationIdDefinition = RegExp(
    RegExp.escape(_applicationIdDefinitionAnchor),
  );

  static const _beginMarkup =
      '# ----- BEGIN FLUTTER_APP_FLAVOR (autogenerated by flutter_flavorizr) -----';
  static const _endMarkup =
      '# ----- END FLUTTER_APP_FLAVOR (autogenerated by flutter_flavorizr) -----';

  LinuxRunnerCMakeListsProcessor({
    super.input,
    required super.config,
    required super.logger,
  });

  @override
  String execute() {
    logger.detail(
      '[$LinuxRunnerCMakeListsProcessor] Processing linux/runner/CMakeLists.txt',
    );

    final cleaned = _cleanupExistingBlock(input!);
    final anchorMatch = _applicationIdDefinition.firstMatch(cleaned);

    if (anchorMatch == null) {
      logger.detail(
        '[$LinuxRunnerCMakeListsProcessor] No `$_applicationIdDefinitionAnchor` found in linux/runner/CMakeLists.txt',
        style: logger.theme.err,
      );

      throw MalformedResourceException(input!);
    }

    logger.detail(
      '[$LinuxRunnerCMakeListsProcessor] Found APPLICATION_ID definition, forwarding FLUTTER_APP_FLAVOR',
    );

    final rest = stripLeadingLineBreaks(cleaned.substring(anchorMatch.end));

    final buffer = StringBuffer(cleaned.substring(0, anchorMatch.end));
    buffer.writeln();
    buffer.writeln();
    _appendBlock(buffer);
    buffer.writeln();
    buffer.writeln();
    buffer.write(rest);

    logger.detail(
      '[$LinuxRunnerCMakeListsProcessor] linux/runner/CMakeLists.txt processed',
      style: logger.theme.success,
    );

    return buffer.toString();
  }

  String _cleanupExistingBlock(String content) =>
      cleanupMarkupBlock(content, _beginMarkup, _endMarkup);

  void _appendBlock(StringBuffer buffer) {
    buffer.writeln(_beginMarkup);
    buffer.writeln(
      'if(DEFINED FLUTTER_APP_FLAVOR AND NOT FLUTTER_APP_FLAVOR STREQUAL "")',
    );
    buffer.writeln(
      '  add_definitions(-DFLUTTER_APP_FLAVOR="\${FLUTTER_APP_FLAVOR}")',
    );
    buffer.writeln('endif()');
    buffer.write(_endMarkup);
  }

  @override
  String toString() => 'LinuxRunnerCMakeListsProcessor';
}
