/*
 * Copyright (c) 2024 Angelo Cassano
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

import 'package:flutter_flavorizr/src/exception/malformed_resource_exception.dart';
import 'package:flutter_flavorizr/src/parser/models/flavors/flavor.dart';
import 'package:flutter_flavorizr/src/processors/commons/string_processor.dart';

class LinuxMyApplicationProcessor extends StringProcessor {
  // Present when `my_application.cc` already declares a `window_title`
  // variable (newer `flutter create` templates with flavor support).
  static final RegExp _windowTitleVariable = RegExp(
    r'const gchar\* window_title = "[^"]*";',
  );

  // Present on older templates, where the title is set via two inline
  // string literals instead of a variable.
  static final RegExp _headerBarTitleLiteral = RegExp(
    r'gtk_header_bar_set_title\(header_bar, "([^"]*)"\);',
  );
  static final RegExp _windowTitleLiteral = RegExp(
    r'gtk_window_set_title\(window, "([^"]*)"\);',
  );
  static final RegExp _useHeaderBarAnchor = RegExp(
    r'[ \t]*if \(use_header_bar\) \{\n',
  );

  static const _beginMarkup =
      '  // ----- BEGIN window_title (autogenerated by flutter_flavorizr) -----';
  static const _endMarkup =
      '  // ----- END window_title (autogenerated by flutter_flavorizr) -----';

  LinuxMyApplicationProcessor({
    super.input,
    required super.config,
    required super.logger,
  });

  @override
  String execute() {
    logger.detail(
      '[$LinuxMyApplicationProcessor] Processing linux/runner/my_application.cc',
    );

    final cleaned = _cleanupExistingBlock(input!);
    final withVariable = _ensureWindowTitleVariable(cleaned);

    final anchorMatch = _windowTitleVariable.firstMatch(withVariable);
    if (anchorMatch == null) {
      logger.detail(
        '[$LinuxMyApplicationProcessor] No window_title declaration found in my_application.cc',
        style: logger.theme.err,
      );

      throw MalformedResourceException(input!);
    }

    logger.detail(
      '[$LinuxMyApplicationProcessor] Found window_title declaration, injecting per-flavor overrides',
    );

    final rest = withVariable
        .substring(anchorMatch.end)
        .replaceFirst(RegExp(r'^\n+'), '');

    final buffer = StringBuffer(withVariable.substring(0, anchorMatch.end));
    buffer.writeln();
    _appendBlock(buffer);
    buffer.writeln();
    buffer.write(rest);

    logger.detail(
      '[$LinuxMyApplicationProcessor] linux/runner/my_application.cc processed',
      style: logger.theme.success,
    );

    return buffer.toString();
  }

  /// Older `flutter create` templates set the header bar / window title via
  /// two inline string literals instead of a `window_title` variable.
  /// Refactor those into a variable declaration so the flavor-aware block
  /// has something to override.
  String _ensureWindowTitleVariable(String content) {
    if (_windowTitleVariable.hasMatch(content)) {
      return content;
    }

    final headerBarMatch = _headerBarTitleLiteral.firstMatch(content);
    final anchorMatch = _useHeaderBarAnchor.firstMatch(content);

    if (headerBarMatch == null || anchorMatch == null) {
      return content;
    }

    final defaultTitle = headerBarMatch.group(1)!;

    var result = content.replaceAll(
      _headerBarTitleLiteral,
      'gtk_header_bar_set_title(header_bar, window_title);',
    );
    result = result.replaceAll(
      _windowTitleLiteral,
      'gtk_window_set_title(window, window_title);',
    );

    final insertionPoint = anchorMatch.start;
    return '${result.substring(0, insertionPoint)}'
        '  const gchar* window_title = "$defaultTitle";\n'
        '${result.substring(insertionPoint)}';
  }

  String _cleanupExistingBlock(String content) {
    final escapedBegin = RegExp.escape(_beginMarkup.trim());
    final escapedEnd = RegExp.escape(_endMarkup.trim());

    final regex = RegExp(
      r'\n*[ \t]*' + escapedBegin + r'\n.*?\n[ \t]*' + escapedEnd + r'\n*',
      dotAll: true,
      multiLine: true,
    );

    return content.replaceAll(regex, '');
  }

  void _appendBlock(StringBuffer buffer) {
    buffer.writeln(_beginMarkup);
    buffer.writeln('  #ifdef FLUTTER_APP_FLAVOR');

    final entries = config.linuxFlavors.entries.toList(growable: false);
    for (int i = 0; i < entries.length; i++) {
      final MapEntry<String, Flavor> entry = entries[i];
      final keyword = i == 0 ? 'if' : '} else if';

      buffer.writeln(
        '  $keyword (g_strcmp0(FLUTTER_APP_FLAVOR, "${entry.key}") == 0) {',
      );
      buffer.writeln('    window_title = "${_escape(entry.value.app.name)}";');
    }

    buffer.writeln('  }');
    buffer.writeln('  #endif');
    buffer.write(_endMarkup);
  }

  String _escape(String value) => value.replaceAll('"', '\\"');

  @override
  String toString() => 'LinuxMyApplicationProcessor';
}
