/*
 * Copyright (c) 2024 Angelo Cassano
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

import 'package:flutter_flavorizr/src/exception/malformed_resource_exception.dart';
import 'package:flutter_flavorizr/src/parser/models/flavors/flavor.dart';
import 'package:flutter_flavorizr/src/processors/commons/string_processor.dart';
import 'package:flutter_flavorizr/src/utils/linux_utils.dart';

class LinuxCMakeListsProcessor extends StringProcessor {
  static final RegExp _applicationIdSetter = RegExp(
    r'set\(APPLICATION_ID "[^"]*"\)',
  );

  static const _beginMarkup =
      '# ----- BEGIN APPLICATION_ID (autogenerated by flutter_flavorizr) -----';
  static const _endMarkup =
      '# ----- END APPLICATION_ID (autogenerated by flutter_flavorizr) -----';

  LinuxCMakeListsProcessor({
    super.input,
    required super.config,
    required super.logger,
  });

  @override
  String execute() {
    logger.detail(
      '[$LinuxCMakeListsProcessor] Processing linux/CMakeLists.txt',
    );

    final cleaned = _cleanupExistingBlock(input!);
    final anchorMatch = _applicationIdSetter.firstMatch(cleaned);

    if (anchorMatch == null) {
      logger.detail(
        '[$LinuxCMakeListsProcessor] No APPLICATION_ID setter found in linux/CMakeLists.txt',
        style: logger.theme.err,
      );

      throw MalformedResourceException(input!);
    }

    logger.detail(
      '[$LinuxCMakeListsProcessor] Found APPLICATION_ID setter, injecting per-flavor overrides',
    );

    final rest = stripLeadingLineBreaks(cleaned.substring(anchorMatch.end));

    final buffer = StringBuffer(cleaned.substring(0, anchorMatch.end));
    buffer.writeln();
    buffer.writeln();
    _appendBlock(buffer);
    buffer.writeln();
    buffer.writeln();
    buffer.write(rest);

    logger.detail(
      '[$LinuxCMakeListsProcessor] linux/CMakeLists.txt processed',
      style: logger.theme.success,
    );

    return buffer.toString();
  }

  String _cleanupExistingBlock(String content) =>
      cleanupMarkupBlock(content, _beginMarkup, _endMarkup);

  void _appendBlock(StringBuffer buffer) {
    buffer.writeln(_beginMarkup);
    buffer.writeln('if(DEFINED FLUTTER_APP_FLAVOR)');

    final entries = config.linuxFlavors.entries.toList(growable: false);
    for (int i = 0; i < entries.length; i++) {
      final MapEntry<String, Flavor> entry = entries[i];
      final keyword = i == 0 ? 'if' : 'elseif';

      buffer.writeln('  $keyword(FLUTTER_APP_FLAVOR STREQUAL "${entry.key}")');
      buffer.writeln(
        '    set(APPLICATION_ID "${escapeQuotedString(entry.value.linux!.applicationId)}")',
      );
    }

    buffer.writeln('  endif()');
    buffer.writeln('endif()');
    buffer.write(_endMarkup);
  }

  @override
  String toString() => 'LinuxCMakeListsProcessor';
}
