name: Build Android

on:
  workflow_call:
    inputs:
      flavor:
        required: true
        type: string
      working-directory:
        required: true
        type: string

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: ./.github/actions/setup
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Build Android AAB
        working-directory: ${{ inputs.working-directory }}
        run: |
          flutter build appbundle --release --flavor ${{ inputs.flavor }}