name: Run Tests and Analyze source code

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Testing
    uses: ./.github/workflows/test.yml

  analyze:
    name: Testing
    uses: ./.github/workflows/analyze.yml

  build_android_example:
    needs:
      - test
      - analyze
    name: Build
    uses: ./.github/workflows/build_android_example.yml

  build_ios_example:
    needs:
      - test
      - analyze
    name: Build
    uses: ./.github/workflows/build_ios_example.yml

  release:
    needs:
      - build_android_example
      - build_ios_example
    name: Release
    uses: ./.github/workflows/release.yml