name: Run Tests and Analyze source code

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Testing
    uses: ./.github/workflows/test.yml

  analyze:
    name: Testing
    uses: ./.github/workflows/analyze.yml

  build_android_example:
    needs:
      - test
      - analyze
    name: Build (Example:${{ matrix.flavor }})
    strategy:
      matrix:
        flavor: [apple, banana]
    uses: ./.github/workflows/android.yml
    with:
      working-directory: example/android
      flavor: ${{ matrix.flavor }}

  build_ios_example:
    needs:
      - test
      - analyze
    name: Build (Example:${{ matrix.flavor }})
    strategy:
      matrix:
        flavor: [apple, banana]
    uses: ./.github/workflows/ios.yml
    with:
      working-directory: example/ios
      flavor: ${{ matrix.flavor }}

  release:
    needs:
      - build_android_example
      - build_ios_example
    name: Release
    uses: ./.github/workflows/release.yml