name: Run Tests and Analyze source code

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Testing
    uses: ./.github/workflows/test.yml

  analyze:
    name: Testing
    uses: ./.github/workflows/analyze.yml

  build:
    needs:
      - test
      - analyze
    strategy:
      matrix:
        flavor: [apple, banana]
        platform: [android, ios]
        working-directory: [example]
    uses: ./.github/workflows/build.yml
    with:
      flavor: ${{ matrix.flavor }}
      platform: ${{ matrix.platform }}
      working-directory: ${{ matrix.working-directory }}

  release:
    needs:
      - build
    name: Release
    uses: ./.github/workflows/release.yml